![](../docs/banner.png)

# NumPy


## Exercises

### 1.

Import numpy under the alias `np`.

In [1]:
import numpy as np

### 2.

Create the following arrays:

1. Create an array of 5 zeros.
2. Create an array of 10 ones.
3. Create an array of 5 3.141s.
4. Create an array of the integers 1 to 20.
5. Create a 5 x 5 matrix of ones with a dtype `int`.

In [13]:
array=[5, 3., 141]
array_01=np.zeros(5)
array_02=np.ones(10)
array_03=np.array(array)
array_04=np.arange(1,21)
array_05=np.ones((5,5), dtype=int)

### 3.

Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [21]:
np.random.randn(3,3,3).reshape(27,)

array([ 1.03732027,  1.46684552,  1.22990918,  0.0097433 , -0.8884216 ,
       -1.0827526 ,  0.11247119, -1.4833817 ,  0.48748504,  0.80449345,
       -1.60371632, -0.47980905,  0.70611913,  0.34644494,  0.32385878,
        0.52831002, -2.39908526, -1.93107616,  0.15141134,  0.27992742,
       -1.14929528,  0.02862205,  0.37848529, -1.23019561, -0.68577421,
       -2.12369122,  0.63961747])

### 4.

Create an array of 20 linearly spaced numbers between 1 and 10.

In [22]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

### 5.

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [56]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

```python
20
```

In [46]:
a[1:, 3:]

array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [48]:
a[1,:]

array([ 6,  7,  8,  9, 10])

```python
array([ 6,  7,  8,  9, 10])
```

In [50]:
a[2:4,: ]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

```python
array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])
```

In [54]:
a[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

```python
array([[ 8,  9],
       [13, 14]])
```

In [10]:
# Your answer here.

### 6.

Calculate the sum of all the numbers in `a`.

In [57]:
a.sum()

325

### 7.

Calculate the sum of each row in `a`.

In [65]:
a.sum(1)

array([ 15,  40,  65,  90, 115])

### 8.

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [62]:
a[a>a.mean()]

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

### 9.

Find the location of the minimum value in the following array `b`:

In [71]:
np.random.seed(123)
b = np.random.randn(10)
b

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025,
        1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

In [79]:
b.argmin()

6

### 10.

Find the location of the maximum value in the following 2D array `c` (hint: there are many ways to do this question, but a quick search on stackoverflow.com will typically help you find the optimum solution for a problem, for example see [post](https://stackoverflow.com/questions/3584243/get-the-position-of-the-biggest-item-in-a-multi-dimensional-numpy-array)):

In [76]:
np.random.seed(123)
c = np.random.randn(3, 2)
c

array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654]])

In [80]:
c.argmax()

5

<hr>
<hr>
<hr>